---
# Set CumulusLinux interfaces

- name: abort uncommit nclu modification
  nclu:
    abort: true

- name: Set interfaces
  nclu:
    commands:
      - add interface {{ item }}
  with_recursive:
    - '{{ cl_interfaces }}'
  register: interfaces

- name: Commit nclu only if interfaces changed
  nclu:
    commit: true
    description: 'Ansible - set interfaces'
  when: interfaces.changed
